FROM ubuntu@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD https://github.com/MrDave/StaticJinjaPlus.git /StaticJinjaPlus

WORKDIR /StaticJinjaPlus

RUN python3 -m venv venv
RUN . venv/bin/activate && pip install -r requirements.txt

VOLUME ["/templates"]
VOLUME ["/build"]

ENTRYPOINT ["/StaticJinjaPlus/venv/bin/python3", "main.py"]
CMD ["--srcpath", "/templates", "--outpath", "/build"]