FROM python:3.11-slim-buster@sha256:c46b0ae5728c2247b99903098ade3176a58e274d9c7d2efeaaab3e0621a53935

ARG CHECKSUM=30d9424df1eddb73912b0e2ad5375fa2c876c8e30906bec91952dfb75dcf220b
ARG STATIC_JINJA_PLUS_VERSION=0.1.1

ADD --checksum=sha256:${CHECKSUM} \
    https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/${STATIC_JINJA_PLUS_VERSION}.tar.gz \
    /tmp/StaticJinjaPlus-${STATIC_JINJA_PLUS_VERSION}.tar.gz

WORKDIR /StaticJinjaPlus
RUN tar xzf /tmp/StaticJinjaPlus-${STATIC_JINJA_PLUS_VERSION}.tar.gz --strip-components=1 && rm /tmp/StaticJinjaPlus-${STATIC_JINJA_PLUS_VERSION}.tar.gz

RUN pip install -r requirements.txt

VOLUME ["/templates"]
VOLUME ["/build"]

ENTRYPOINT ["python3", "main.py"]
CMD ["--srcpath", "/templates", "--outpath", "/build"]